Credentials
fdw/rofi-rbw pull request #12
Opened 2021-05-25 09:54 UTC by tosti007

Hey there, 

In PR #10 we said that it might be nice to have a dedicated `Credentials` class with parsing rather than a `Data` tuple and `extract_[something]` functions. So here is a small implementation to kickstart the idea.

2021-05-26 16:13 UTC, fdw requested changes
Looks good so far, thanks :)

2021-05-26 16:13 UTC, fdw commented on src/rofi_rbw/credentials.py
> +    def from_rbw(data: str) -> 'Credentials':
What do you think about doing this in the constructor? I don't expect any other usage of this class.

2021-05-26 16:13 UTC, fdw commented on src/rofi_rbw/rofi_rbw.py
> +    def execute_action(self, data: Credentials) -> None:
I think we should also rename the parameter then

2021-05-26 16:13 UTC, fdw commented on src/rofi_rbw/rofi_rbw.py
> +    def get_data(self, name: str, folder: str) -> Credentials:
And this method should then also be called "get_credentials"

2021-05-27 14:47 UTC, fdw approved these changes

2021-05-27 14:47 UTC, merged

2021-05-27 14:47 UTC, fdw commented
Thank you :)

2021-05-27 22:14 UTC, tosti007 commented
No problem! Only I did just see that I made a mistake and that the `__init__` of `Credentials` does not store the value of password and username if self, but rather in a non-existent `result` variable.