Implement clearing the clipboard after a given time
fdw/rofi-rbw pull request #41
Opened 2022-02-16 10:48 UTC by das-s

An implementation for clearing the password in the clipboard, very similar existing ones, e.g. <https://github.com/mattydebie/bitwarden-rofi/>. It will also kill your clipboard if you copied something else in between but that is to be expected.

Disclaimer:  This is not tested on Wayland. Could someone else check, please? Once confirmation is given I'll convert the draft.

2022-02-16 16:56 UTC, fdw reviewed
That looks already quite good, thank you!

One thing I'm wondering is whether it makes sense to consolidate all the `if clear > 0`. One idea could be to keep `copy_to_clipboard` as is, add a `clear_clipboard` to all subclasses and have a new `copy_to_clipboard_and_clear` only in `Clipboarder` that calls the others.
What do you think?

2022-02-16 16:56 UTC, fdw commented on src/rofi_rbw/clipboarder.py
> +            run(['wl-copy', '--clear'])
I also don't have Wayland running, but it conforms to `wl-copy`'s documentation, so it's good enough for me :)

2022-02-16 16:56 UTC, fdw commented on src/rofi_rbw/rofi_rbw.py
> +            '--clear-period',
Not sure about "period" - it's not getting cleared periodically. Maybe "--clear-after" or just "--clear"?

2022-02-16 16:56 UTC, fdw commented on src/rofi_rbw/rofi_rbw.py
> +            help='Choose the time in seconds passwords stay in your clipboard. When not set or <= 0, will keep indefinitely.'
I think this deserves a note in the readme es well ;)

2022-02-16 17:58 UTC, das-s commented on src/rofi_rbw/rofi_rbw.py
> +            '--clear-period',
I meant period more in the sense of duration/time period but I understand the concerns. "--clear" was actually what I had before so I'd settle for that.

2022-02-16 18:25 UTC, das-s commented
> One thing I&rsquo;m wondering is whether it makes sense to consolidate all
> the `if clear > 0`. One idea could be to keep `copy_to_clipboard` as
> is, add a `clear_clipboard` to all subclasses and have a new
> `copy_to_clipboard_and_clear` only in `Clipboarder` that calls the
> others. What do you think?

Sounds sensible to me! Though, what do you say about having the call to
`clear_clipboard` [here](https://github.com/fdw/rofi-rbw/blob/main/src/rofi_rbw/rofi_rbw.py#L189):

``` python
    elif self.args.action == self.Action.COPY_PASSWORD:
        self.clipboarder.copy_to_clipboard(cred.password)
        if self.args.clear > 0:
            time.sleep(self.args.clear)
            self.clipboarder.clear_clipboard()
``` 
That would erase the necessity of having `copy_to_clipboard_and_clear`.

2022-02-16 19:51 UTC, fdw commented
I had also thought about something like that. The one thing that I like less about this approach is that it's coincidence that all need the `time.sleep` call, and it's not something `rofi-rbw` should care about; it's something the `Clipboarder` should encapsulate.

Differently put, what if there is one that has its own "clear after n seconds" call? Or even "copy and delete after n seconds"? A clean `Clipboarder` interface should handle that case without needing changes in the caller.

So, maybe something like that would also work:
```python
    elif self.args.action == self.Action.COPY_PASSWORD:
        self.clipboarder.copy_to_clipboard(cred.password)
        self.clipboarder.clear_clipboard(self.args.clear)
```

I think I'd be fine with both implementations (or you can persuade me that calling `time.sleep` is no problem 😉).

2022-02-16 21:30 UTC, das-s commented
> The one thing that I like less about this approach is that it's coincidence that all need the time.sleep call

Well, that's a very good point, I concur. I settled for the last proposal now.

Should I mention the change in CHANGELOG.md?

2022-02-17 15:10 UTC, fdw requested changes

2022-02-17 15:10 UTC, fdw commented on src/rofi_rbw/clipboarder.py
> +    def copy_to_clipboard(self, characters: str, clear: int = 0) -> None:
This is now unnecessary, right?

2022-02-17 15:10 UTC, fdw commented on src/rofi_rbw/clipboarder.py
> +    def clear_clipboard_after(self, clear: int) -> None:
Could you please add the same error as above?

2022-02-17 15:10 UTC, fdw commented
> Should I mention the change in CHANGELOG.md?

Sure, otherwise I have to ;)

2022-02-17 17:05 UTC, das-s commented on src/rofi_rbw/clipboarder.py
> +    def copy_to_clipboard(self, characters: str, clear: int = 0) -> None:
Oops, that slipped by.

2022-02-18 07:19 UTC, merged

2022-02-18 07:19 UTC, fdw commented
Awesome, thank you! 🙂